import type { AuthParams, SecEntity, SecurityProtocol } from "./interface.ts";
import { extractApReq } from "../utils/asn1.ts";

let kerberosModule: typeof import("kerberos") | null = null;

async function loadKerberos(): Promise<typeof import("kerberos")> {
  if (kerberosModule) return kerberosModule;
  kerberosModule = await import("kerberos");
  return kerberosModule;
}

/**
 * Kerberos 5 authentication protocol.
 *
 * Uses the system Kerberos infrastructure (keytab, ticket cache) to
 * authenticate against the XRootD server. Requires:
 * - The `kerberos` npm package (native module, depends on libkrb5)
 * - A valid Kerberos ticket (obtained via `kinit`)
 * - The KRB5CCNAME environment variable or default credential cache
 *
 * Credential format: "krb5" + Kerberos authentication token
 * (generated by krb5_mk_req_extended)
 */
export class Krb5Auth implements SecurityProtocol {
  readonly name = "krb5";
  private entity: SecEntity = { prot: "krb5", uid: 0, gid: 0 };
  private complete = false;

  /**
   * Check if Kerberos authentication is available.
   * Returns true if the `kerberos` npm package can be loaded.
   */
  static isSupported(): boolean {
    try {
      require.resolve("kerberos");
      return true;
    } catch {
      return false;
    }
  }

  async getCredentials(params: AuthParams): Promise<Uint8Array> {
    const kerberos = await loadKerberos();

    // Use the SPN prefix parsed from server secToken (e.g. "host" or "xrootd").
    // Falls back to "xrootd" if the server didn't specify one.
    const servicePrefix = params.spnPrefix || "xrootd";
    const servicePrincipal = `${servicePrefix}@${params.host}`;

    // Initialize the Kerberos client
    const kerberosClient = await kerberos.initializeClient(servicePrincipal);

    // Generate the authentication token (step 1 of the GSSAPI flow)
    // First step: pass empty string as challenge
    const token = await kerberosClient.step("");

    // The token is base64 encoded, decode it to bytes.
    // kerberos.step() calls gss_init_sec_context() which returns a GSS-API
    // InitialContextToken (starts with 0x60), but the XRootD server expects
    // a raw Kerberos AP-REQ (starts with 0x6e). We must strip the GSS-API
    // framing to extract the raw AP-REQ.
    const gssToken = Buffer.from(token, "base64");
    const apReq = extractApReq(gssToken);

    // Encode as "krb5\0" + raw AP-REQ
    // The null terminator is required by the C++ server which uses strcmp()
    // to match the protocol name in the credential buffer.
    const prefix = new TextEncoder().encode("krb5\0");

    const result = new Uint8Array(prefix.length + apReq.length);
    result.set(prefix);
    result.set(apReq, prefix.length);

    this.entity.name = params.username;

    return result;
  }

  async processChallenge(_challenge: Uint8Array): Promise<Uint8Array> {
    this.complete = true;
    return new Uint8Array(0);
  }

  isComplete(): boolean {
    return this.complete;
  }

  getEntity(): SecEntity {
    return this.entity;
  }
}
