import type { AuthParams, SecEntity, SecurityProtocol } from "./interface.ts";

let kerberosModule: typeof import("kerberos") | null = null;

async function loadKerberos(): Promise<typeof import("kerberos")> {
  if (kerberosModule) return kerberosModule;
  kerberosModule = await import("kerberos");
  return kerberosModule;
}

/**
 * Kerberos 5 authentication protocol.
 *
 * Uses the system Kerberos infrastructure (keytab, ticket cache) to
 * authenticate against the XRootD server. Requires:
 * - The `kerberos` npm package (native module, depends on libkrb5)
 * - A valid Kerberos ticket (obtained via `kinit`)
 * - The KRB5CCNAME environment variable or default credential cache
 *
 * Credential format: "krb5" + Kerberos authentication token
 * (generated by krb5_mk_req_extended)
 */
export class Krb5Auth implements SecurityProtocol {
  readonly name = "krb5";
  private entity: SecEntity = { prot: "krb5", uid: 0, gid: 0 };
  private complete = false;

  /**
   * Check if Kerberos authentication is available.
   * Returns true if the `kerberos` npm package can be loaded.
   */
  static isSupported(): boolean {
    try {
      require.resolve("kerberos");
      return true;
    } catch {
      return false;
    }
  }

  async getCredentials(params: AuthParams): Promise<Uint8Array> {
    const kerberos = await loadKerberos();

    // Build the service principal: xrootd@<hostname>
    const servicePrincipal = `xrootd@${params.host}`;

    // Initialize the Kerberos client
    const kerberosClient = await kerberos.initializeClient(servicePrincipal);

    // Generate the authentication token (step 1 of the GSSAPI flow)
    // First step: pass empty string as challenge
    const token = await kerberosClient.step("");

    // The token is base64 encoded, decode it to bytes
    const tokenBytes = Buffer.from(token, "base64");

    // Encode as "krb5\0" + token
    // The null terminator is required by the C++ server which uses strcmp()
    // to match the protocol name in the credential buffer.
    const prefix = new Uint8Array([0x6b, 0x72, 0x62, 0x35, 0x00]); // "krb5\0"

    const result = new Uint8Array(prefix.length + tokenBytes.length);
    result.set(prefix);
    result.set(tokenBytes, prefix.length);

    this.entity.name = params.username;

    return result;
  }

  async processChallenge(_challenge: Uint8Array): Promise<Uint8Array> {
    this.complete = true;
    return new Uint8Array(0);
  }

  isComplete(): boolean {
    return this.complete;
  }

  getEntity(): SecEntity {
    return this.entity;
  }
}
