import type { AuthParams, SecEntity, SecurityProtocol } from "./interface.ts";

let DEBUG_cnt = 0;

let kerberosModule: typeof import("kerberos") | null = null;

async function loadKerberos(): Promise<typeof import("kerberos")> {
  if (kerberosModule) return kerberosModule;
  kerberosModule = await import("kerberos");
  return kerberosModule;
}

/**
 * Kerberos 5 authentication protocol.
 *
 * Uses the system Kerberos infrastructure (keytab, ticket cache) to
 * authenticate against the XRootD server. Requires:
 * - The `kerberos` npm package (native module, depends on libkrb5)
 * - A valid Kerberos ticket (obtained via `kinit`)
 * - The KRB5CCNAME environment variable or default credential cache
 *
 * Credential format: "krb5" + Kerberos authentication token
 * (generated by krb5_mk_req_extended)
 */
export class Krb5Auth implements SecurityProtocol {
  readonly name = "krb5";
  private entity: SecEntity = { prot: "krb5", uid: 0, gid: 0 };
  private complete = false;

  /**
   * Check if Kerberos authentication is available.
   * Returns true if the `kerberos` npm package can be loaded.
   */
  static isSupported(): boolean {
    return false; // TODO: disabled
    try {
      require.resolve("kerberos");
      return true;
    } catch {
      return false;
    }
  }

  async getCredentials(params: AuthParams): Promise<Uint8Array> {
    const kerberos = await loadKerberos();

    // Build the service principal: xrootd@<hostname>
    console.log(`DEBUG: Krb5Auth.getCredentials() called for host=${params.host}, username=${params.username}`);
    const servicePrincipal = `${DEBUG_cnt++ % 2 === 0 ? "xrootd" : "host"}@${params.host}`;

    // Initialize the Kerberos client
    const kerberosClient = await kerberos.initializeClient(servicePrincipal);

    // Generate the authentication token (step 1 of the GSSAPI flow)
    // First step: pass empty string as challenge
    const token = await kerberosClient.step("");

    // The token is base64 encoded, decode it to bytes.
    // kerberos.step() calls gss_init_sec_context() which returns a GSS-API
    // InitialContextToken (starts with 0x60), but the XRootD server expects
    // a raw Kerberos AP-REQ (starts with 0x6e). We must strip the GSS-API
    // framing to extract the raw AP-REQ.
    const gssToken = Buffer.from(token, "base64");
    const apReq = extractApReq(gssToken);

    // Encode as "krb5\0" + raw AP-REQ
    // The null terminator is required by the C++ server which uses strcmp()
    // to match the protocol name in the credential buffer.
    const prefix = new Uint8Array([0x6b, 0x72, 0x62, 0x35, 0x00]); // "krb5\0"

    const result = new Uint8Array(prefix.length + apReq.length);
    result.set(prefix);
    result.set(apReq, prefix.length);

    this.entity.name = params.username;

    return result;
  }

  async processChallenge(_challenge: Uint8Array): Promise<Uint8Array> {
    this.complete = true;
    return new Uint8Array(0);
  }

  isComplete(): boolean {
    return this.complete;
  }

  getEntity(): SecEntity {
    return this.entity;
  }
}

/**
 * Extract a raw Kerberos AP-REQ from a GSS-API InitialContextToken.
 *
 * The `kerberos` npm package calls gss_init_sec_context() which wraps the
 * AP-REQ inside a GSS-API InitialContextToken (ASN.1 tag 0x60). The XRootD
 * server's krb5_rd_req() expects a raw AP-REQ (ASN.1 tag 0x6e), so we
 * must strip the GSS-API framing.
 *
 * GSS-API token layout:
 *   60 [len]                  ← APPLICATION 0 (InitialContextToken)
 *     06 09 [OID bytes]       ← Kerberos 5 OID (1.2.840.113554.1.2.2)
 *     [inner token]           ← contains raw AP-REQ (tag 0x6e)
 */
function extractApReq(token: Uint8Array): Uint8Array {
  // If not a GSS-API token, return as-is (already a raw AP-REQ)
  if (token.length === 0 || token[0] !== 0x60) {
    return token;
  }

  // Search for the AP-REQ tag (0x6e = APPLICATION 14) after the GSS-API header
  for (let i = 1; i < token.length; i++) {
    if (token[i] === 0x6e) {
      const lenResult = parseAsn1Length(token, i + 1);
      if (lenResult) {
        const apReqEnd = lenResult.offset + lenResult.length;
        return token.slice(i, apReqEnd);
      }
    }
  }

  // Fallback: return the original token
  return token;
}

/**
 * Parse an ASN.1 DER length field.
 *
 * Short form: first byte < 0x80 → that byte is the length.
 * Long form:  first byte >= 0x80 → low 7 bits = number of subsequent bytes
 *             that encode the length as a big-endian integer.
 */
function parseAsn1Length(
  data: Uint8Array,
  offset: number,
): { offset: number; length: number } | null {
  if (offset >= data.length) return null;

  const firstByte = data[offset]!;
  if (firstByte < 0x80) {
    return { offset: offset + 1, length: firstByte };
  }

  const numBytes = firstByte & 0x7f;
  if (numBytes === 0 || offset + 1 + numBytes > data.length) return null;

  let length = 0;
  for (let i = 0; i < numBytes; i++) {
    length = (length << 8) | data[offset + 1 + i]!;
  }
  return { offset: offset + 1 + numBytes, length };
}
